"""Emit docs/glossary.md's cell-type entries as JSON for the Android app.

The phone shows an explanation when a readout row is tapped. That text is not
copied into Java: it is generated from the glossary at build time, so the
documentation stays the single source of truth and on-device text cannot
quietly drift away from the reviewed docs.

Each entry is keyed by every cell-type name in its bolded term, so a display
type ('MDN') finds the entry that documents it ('DNp09 and MDN'). The shared
'DN' entry travels with every descending-neuron type as context, because it
carries the biological-role vs engineered-BCI distinction that must not be
dropped on the way to the screen.

Written as plain text, not markdown: the app renders it directly.
"""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/glossary.md'

# Display type -> the glossary term that documents it, where the two differ.
ALIASES = {'DLMn': 'DLM'}

# Prepended to every descending-neuron entry: the honesty framing lives there.
SHARED_CONTEXT = {t: 'DN' for t in
                  ['DNa02', 'DNp09', 'MDN', 'MN9', 'DNp20', 'DNpe017']}


def plain(text):
    """Markdown to the plain text the app draws. Links keep their URL."""
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'\1 (\2)', text)
    # Code spans are set aside before emphasis is stripped: they contain bare
    # asterisks ('DNa*', 'DNp*') that an italic pattern would otherwise eat.
    spans = []
    def stash(m):
        spans.append(m.group(1))
        return f'\x00{len(spans) - 1}\x00'
    text = re.sub(r'`([^`]*)`', stash, text)
    text = text.replace('**', '')
    text = re.sub(r'(?<!\*)\*(?!\*)([^*\n]+)\*(?!\*)', r'\1', text)
    return re.sub(r'\x00(\d+)\x00', lambda m: spans[int(m.group(1))], text)


def parse(markdown):
    """Top-level '- **Term** — body' entries, with their indented sub-bullets."""
    entries, section, current = [], None, None
    for line in markdown.splitlines():
        heading = re.match(r'^##\s+(.*)', line)
        if heading:
            section, current = heading.group(1).strip(), None
            continue
        # A term may name several cells: '- **DNp09** and **MDN — …** — body'.
        start = re.match(r'^- ((?:\*\*[^*]+\*\*)(?:\s+and\s+\*\*[^*]+\*\*)*)\s*(.*)', line)
        if start:
            current = {'term': start.group(1).strip(), 'section': section,
                       'lines': [start.group(2).strip()]}
            entries.append(current)
            continue
        if current is not None and line.strip():
            if line.startswith(('  ', '\t')):
                stripped = line.strip()
                # Keep a nested bullet on its own line; fold prose continuations.
                current['lines'].append(
                    '\n' + stripped if stripped.startswith('- ') else stripped)
            else:
                current = None
        elif not line.strip():
            current = None
    for e in entries:
        body = ' '.join(e['lines']).replace(' \n', '\n')
        text = plain(re.sub(r'[ \t]+', ' ', body)).strip()
        # Drop the dash that separated the term from its definition in the list.
        e['text'] = re.sub(r'^[—–-]\s*', '', text)
    return entries


def names(term):
    """Cell-type keys a term documents: 'DNp09 and MDN' -> both; 'DLM — …' -> DLM."""
    out = []
    for part in term.split(' and '):
        part = plain(part).strip()
        # 'DLM — Dorsal Longitudinal Muscle motor neuron' keys on 'DLM'.
        out.append(re.split(r'\s+[—–-]\s+', part)[0].strip())
    return [x for x in out if x]


def export(out_path):
    markdown = SOURCE.read_text()
    entries = parse(markdown)
    by_name = {}
    for e in entries:
        for name in names(e['term']):
            by_name[name] = e
    if not by_name:
        raise ValueError(f'No glossary entries parsed from {SOURCE}')

    payload = {}
    for name, e in by_name.items():
        item = {'title': plain(e['term']), 'section': e['section'] or '',
                'text': e['text']}
        shared = SHARED_CONTEXT.get(name)
        if shared and shared != name and shared in by_name:
            item['context'] = by_name[shared]['text']
        payload[name] = item
    for alias, target in ALIASES.items():
        if target in payload and alias not in payload:
            payload[alias] = payload[target]

    document = {
        'source': str(SOURCE.relative_to(ROOT)),
        'source_sha256': hashlib.sha256(markdown.encode()).hexdigest(),
        'note': 'Generated by doom/export_glossary.py. Edit docs/glossary.md, not this file.',
        'entries': payload,
    }
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(document, indent=2, sort_keys=True) + '\n')
    print(json.dumps({'out': str(out_path), 'entries': sorted(payload),
                      'source_sha256': document['source_sha256']}, indent=2))
    return document


if __name__ == '__main__':
    import sys
    if len(sys.argv) != 2:
        raise SystemExit('usage: python -m doom.export_glossary <out.json>')
    export(sys.argv[1])
